"""Sniff's answers, frozen before sniff is rebuilt from data.

2.0 moves format detection out of the hand-ordered checks in
`core/infra/sniff.py` into per-format records (docs/contract/architecture-2.0.md
section 5). The check order there is a contract enforced only by comments --
RIFF/WAVE before RIFF/NIKS, the MP4 ftyp probe before the ID3 fallbacks, the
extension gates for PT2, STC, PMD and the MPC family -- so a rebuild that moves
one check can reroute a class of files and no test would say so.

This records what sniff says TODAY for every seed, in a set of variations that
reach the order and the gates: the seed as built, without its extension, with
every other seed's extension, truncated, padded, and with its first byte
flipped. A rebuild passes only if every answer is unchanged. When sniff is
meant to change, regenerate on purpose and read the diff:

    ACIDCAT_WRITE_GOLDEN=1 python -m pytest tests/test_sniff_golden.py

The cross-extension grid is stored only where the answer differs from the same
bytes with no extension, which is where the extension gates live.
"""

import os
import pathlib

import pytest

import seeds
from acidcat.core.infra.sniff import sniff, sniff_bytes

GOLDEN = pathlib.Path(__file__).parent / "golden" / "sniff.tsv"


def _variants(b):
    yield "as-built", b, None
    yield "head16", b[:16], None
    yield "head256", b[:256], None
    yield "zero-pad-tail", b + b"\x00" * 1024, None
    yield "zero-pad-front", b"\x00" * 16 + b, None
    yield "first-byte-flipped", bytes([b[0] ^ 0xFF]) + b[1:] if b else b, None


def _answers(tmp):
    """{case: answer} for the whole grid, answer being the id or '-'."""
    out = {}
    exts = sorted({seeds.suffix(f) for f in seeds.SEEDS} | {".bin"})
    path = os.path.join(tmp, "specimen")

    def ask(data, ext):
        p = path + ext
        with open(p, "wb") as fh:
            fh.write(data)
        try:
            return sniff(p) or "-"
        finally:
            os.unlink(p)

    for fmt in sorted(seeds.SEEDS):
        b, ext = seeds.build(fmt), seeds.suffix(fmt)
        for name, data, _ in _variants(b):
            out[f"{fmt}\t{name}\t{ext}"] = ask(data, ext)
        bare = ask(b, ".bin")
        out[f"{fmt}\tas-built\t.bin"] = bare
        out[f"{fmt}\tsniff_bytes\t-"] = sniff_bytes(b[:16]) or "-"
        for other in exts:
            if other in (ext, ".bin"):
                continue
            got = ask(b, other)
            if got != bare:
                out[f"{fmt}\tas-built\t{other}"] = got
    return out


def _read():
    rows = {}
    for line in GOLDEN.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        fmt, variant, ext, answer = line.split("\t")
        rows[f"{fmt}\t{variant}\t{ext}"] = answer
    return rows


def _write(rows):
    GOLDEN.parent.mkdir(exist_ok=True)
    lines = ["# format\tvariant\textension\tsniff answer ('-' = none)",
             "# generated by tests/test_sniff_golden.py; regenerate with "
             "ACIDCAT_WRITE_GOLDEN=1"]
    lines += [f"{k}\t{v}" for k, v in sorted(rows.items())]
    GOLDEN.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_sniff_answers_are_unchanged(tmp_path):
    got = _answers(str(tmp_path))
    if os.environ.get("ACIDCAT_WRITE_GOLDEN"):
        _write(got)
        pytest.skip(f"wrote {len(got)} answers to {GOLDEN.name}")
    want = _read()
    changed = [(k, want.get(k), got.get(k))
               for k in sorted(set(want) | set(got)) if want.get(k) != got.get(k)]
    assert not changed, (
        f"{len(changed)} sniff answer(s) changed (format, variant, extension: "
        "was -> now):\n" + "\n".join(
            f"  {k.replace(chr(9), ', ')}: {a} -> {b}" for k, a, b in changed[:25]))


def test_the_golden_file_covers_every_seed():
    """Guards the guard: a seed added without regenerating is not covered."""
    covered = {k.split("\t")[0] for k in _read()}
    missing = sorted(set(seeds.SEEDS) - covered)
    assert not missing, ("seeds with no golden sniff answers; regenerate with "
                         "ACIDCAT_WRITE_GOLDEN=1: " + ", ".join(missing))


def test_the_seeds_themselves_sniff_as_declared():
    """The as-built answer for each seed is what seeds.py says it should be,
    so the golden file cannot freeze a seed that was already wrong."""
    rows = _read()
    wrong = []
    for fmt in seeds.SEEDS:
        want = seeds.sniffs_as(fmt) or "-"
        got = rows.get(f"{fmt}\tas-built\t{seeds.suffix(fmt)}")
        if got != want:
            wrong.append(f"{fmt}: golden {got}, seeds.py says {want}")
    assert not wrong, "\n".join(wrong)
